# Esencial
ChrootEveryone             yes
Daemonize                  no
NoAnonymous                yes

# MySQL
MySQLConfigFile            /etc/pure-ftpd/pureftpd-mysql.conf
# CreateHomeDir está deshabilitado. 'gestorftp.py' ya se encarga
# CreateHomeDir              yes

# Seguridad Básica
MinUID                     1000
Umask                      133:022
NoChmod                    yes
NoRename                   yes
CustomerProof              yes

# Red
PassivePortRange          30000 30009

# Sistema
PIDFile                   /run/pure-ftpd.pid

# Seguridad TLS (Forzar cifrado)
TLS                        2
TLSCipherSuite             HIGH
CertFile                   /etc/ssl/private/pure-ftpd/pure-ftpd.pem
