MYSQLSocket     /var/lib/mysql/mysql.sock
MYSQLUser       ftpuser
MYSQLDatabase   ftpdb
MYSQLCrypt      crypt
MYSQLPassword 	$MYSQLPASSWD
MYSQLGetPW      SELECT Password FROM users WHERE User="\\L" AND status="1"
MYSQLGetUID     SELECT Uid FROM users WHERE User="\\L" AND status="1"
MYSQLGetGID     SELECT Gid FROM users WHERE User="\\L" AND status="1"
MYSQLGetDir     SELECT Dir FROM users WHERE User="\\L" AND status="1"
MYSQLGetQTAFS   SELECT QuotaFiles FROM users WHERE User="\\L" AND status="1"
MYSQLGetQTASZ   SELECT QuotaSize FROM users WHERE User="\\L" AND status="1"

